export const ADD_USERS = 'ADD_USERS';
export const USERS_FAILED = 'USERS_FAILED';
export const USERS_LOADING = 'USERS_LOADING';
export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const ADD_FEEDBACK = 'ADD_FEEDBACK';
export const ADD_LEADERS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';
export const PROMOS_LOADING = 'PROMOS_LOADING';
export const ADD_PROMOS = 'ADD_PROMOS';
export const PROMOS_FAILED = 'PROMOS_FAILED';
export const ADD_DISHES = 'ADD_DISHES';
export const DISHES_FAILED = 'DISHES_FAILED';
export const DISHES_LOADING = 'DISHES_LOADING';
export const LEADERS_FAILED = 'DISHES_FAILED';
export const LEADERS_LOADING = 'DISHES_LOADING';
/* export const GET_ERRORS = 'GET_ERRORS'; */
/* export const USER_LOADING = 'USER_LOADING'; */
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const LOGIN_FAILED = 'LOGIN_FAILED ';
export const LOGIN_LOADING = 'LOGIN_LOADING';

export const REGISTER_FAILED = 'REGISTER_FAILED ';
export const REGISTER_LOADING = ' REGISTER_LOADING ';
